version: "3.9"

services:
  server-nginx:
    build:
      context: ./docker_stack/nginx/.
    depends_on:
      - php82
      - mysql8
    container_name: server-nginx
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
  php82:
    build:
      context: ./docker_stack/php/.
    container_name: php82
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel
  mysql8:
    image: mysql:8.0.28
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=42505856 --general-log=1 --general-log-file=/logs/general-log.log
    restart: always
    ports:
      - 3310:3306
    volumes:
      - volume-mysql:/var/lib/mysql
      - ./docker_stack/mysql/logs:/logs
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - laravel
  npm:
    image: node:alpine3.18
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel
networks:
  laravel:
    name: laravel
volumes:
  volume-mysql:
    name: volume-mysql





